services:
  db:
    image: mysql:8.4.0
    container_name: mysql
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    restart: always
    healthcheck:
      test: ['CMD', 'mysql', '-h', 'localhost', '-u', '${MYSQL_USER}', '-p${MYSQL_PASSWORD}', '-e', 'SELECT 1']
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile-development
    container_name: backend
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      db:
        condition: service_healthy
volumes:
  data:
