openapi: 3.1.0

info:
  title: Virtual Life
  version: '2.0'

servers:
  - url: http://localhost:3000

components:
  parameters:
    global-id:
      name: id
      schema:
          type: string
      in: path
      required: true
    global-userId:
      name: userId
      schema:
          type: string
      in: path
      required: true
    global-postId:
      name: postId
      schema:
        type: string
      in: path
      required: true
  x-global-variables:
    searchPaginate:
      type: object
      properties:
        limit:
          type: number
        offset:
          type: number
      required: [limit, offset]
    searchSortOrder:
      type: string
      enum: [asc, desc]
      required: [orderBy, sortOrder]