paths:
  /reactions:
    post:
      tags: [Reaction]
      summary: Create a reaction
      description: Create a reaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReaction'
        required: true
      responses:
        201:
          description: Success
        400:
          description: Failed
        500:
          description: Failed
  /reactions/{id}:
    get:
      tags: [Reaction]
      summary: Get a reaction of an activity
      description: Get a reaction
      parameters:
        - $ref: '#/components/parameters/global-id'
      responses:
        200:
          description: Success
        500:
          description: Failed
    delete:
      tags: [Reaction]
      summary: Delete a reaction
      description: Delete a reaction
      parameters:
        - $ref: '#/components/parameters/global-id'
      responses:
        200:
          description: Success
        404:
          description: Not found
        500:
          description: Failed

components:
  schemas:
    CreateReaction:
      type: object
      properties:
        activityId:
          type: string
        activityKind:
          type: string
          enum: ['post', 'comment']
        reactionKind:
          type: string
          enum: ['like', 'love', 'sad', 'laugh', 'angry']
      required: [activityId, activityKind, reactionKind]
    Reaction:
      type: object
      properties:
        authorId:
          type: string
        reactionKind:
          type: string
