paths:
  /comments:
    post:
      tags: [Comment]
      summary: Create a new Comment
      description: Create a new Comment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateComment'
            example:
              postId: 1
              parentCommentId: 1
              commentText: 'My comment'
        required: true
      responses:
        201:
          description: Success
        400:
          description: Failed
        500:
          description: Failed
  /comments/{parentCommentId}:
    get:
      tags: [Comment]
      summary: Get comments for a post or replies for a comment
      description: Get comments for a post or replies for a comment
      parameters:
        - $ref: '#/components/parameters/parentCommentId'
      responses:
        200:
          description: Success
          content:
            application/schema:
              schema:
                $ref: '#/components/schemas/Comments'
        500:
          description: Failed
  /comments/{commentId}:
    patch:
      tags: [Comment]
      summary: Update a coment
      description: Update a coment
      parameters:
        - $ref: '#/components/parameters/commentId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateComment'
      responses:
        200:
          description: Success
        400:
          description: Failed
        404:
          description: Comment not found
        500:
          description: Failed
    delete:
      tags: [Comment]
      summary: Delete a comment
      description: Delete a comment
      parameters:
        - $ref: '#/components/parameters/commentId'
      responses:
        200:
          description: Success
        404:
          description: Comment not found
        500:
          description: Failed

components:
  schemas:
    CreateComment:
      type: object
      properties:
        postId:
          type: number
        parentCommentId:
          type: number
        commentText:
          type: string
      required: [postId, parentCommentId, commentText]
    Comment:
      type: object
      properties:
        id:
          type: number
        authorId:
          type: number
        commentText:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        count_replies:
          type: number
    Comments:
      type: array
      items:
        $ref: '#/components/schemas/Comment'
    UpdateComment:
      type: object
      properties:
        commentText:
          type: string
  parameters:
    commentId:
      name: commentId
      schema:
        type: string
      in: path
    parentCommentId:
      name: parentCommentId
      schema:
        type: string
      in: path
